name: CI

on:
  push:
    branches: [main, develop, feature/archiving-depencies-job]
  pull_request:
    branches: [main, develop, 'feature/**']

jobs:
  install-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1
          cache: 'npm'

      - name: install dependencies
        run: npm install

      - name: check
        run: tar -czvf node_modules.tar node_modules/

      - name: check
        run: gzip node_modules.tar 

      - name: check
        run: ls -la
      
  lint:
    needs: [install-dependency]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1
          cache: 'npm'
          
      - name: Install dependency
        run: npm install
        
      - name : Run linter
        run: npm run lint
