name: Storybook

on:
  push:
    #paths: ["public/**"]
    paths: ["src/stories/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install Dependencies and Build Storybook
      - name : Npm Install and Build
        run: |
          npm install
          npm run build-storybook
      # Deploy Storybook to GitHub Pages
      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          #folder: public # output folder from package.json build-storybook
          folder: src/stories
          
